import random
import datetime

# Lists for realistic Vietnamese data generation
FIRST_NAMES_MALE = ["Văn", "Hữu", "Thành", "Công", "Đức", "Minh", "Quang", "Bảo", "Tuấn", "Hoàng", "Anh", "Thái", "Gia", "Xung", "Ngọc"]
FIRST_NAMES_FEMALE = ["Thị", "Ngọc", "Phương", "Thanh", "Kim", "Bích", "Thu", "Mai", "Ánh", "Hồng", "Diệu", "Lan", "Quỳnh", "Trinh", "Tuyết"]
MID_NAMES_MALE = ["Hùng", "Dũng", "Nam", "Sơn", "Việt", "Phong", "Phúc", "Quý", "Khánh", "Trung", "Cường", "Bách", "Tuấn", "Long", "Hiếu"]
MID_NAMES_FEMALE = ["Thảo", "Hoa", "Anh", "Linh", "Hằng", "Nhi", "Hương", "Trang", "Nhung", "Chi", "Duyên", "Loan", "Vy", "Ly", "Yến"]
LAST_NAMES = ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Nô", "Dương", "Lý"]

DEPARTMENTS = [
    "Ban Giám Đốc", "Phòng Kỹ thuật", "Phòng Thiết kế", "Phòng Nhân sự", 
    "Phòng Kinh doanh", "Phòng Marketing", "Phòng Tài chính - Kế toán", 
    "Phòng Công nghệ thông tin", "Phòng Logistics", "Phòng Nghiên cứu & Phát triển"
]

POSITIONS = {
    "Ban Giám Đốc": ["Giám đốc Điều hành", "Trợ lý Giám đốc", "Thư ký Ban Giám đốc"],
    "Phòng Kỹ thuật": ["Kỹ sư Phần mềm", "Kỹ sư Hệ thống", "Kỹ sư QA", "Trưởng phòng Kỹ thuật"],
    "Phòng Thiết kế": ["Chuyên viên UI/UX", "Senior Designer", "Motion Designer", "Trưởng phòng Thiết kế"],
    "Phòng Nhân sự": ["Chuyên viên Nhân sự", "Trưởng phòng Nhân sự", "HRBP", "Chuyên viên Đào tạo"],
    "Phòng Kinh doanh": ["Chuyên viên Kinh doanh", "Trưởng phòng Kinh doanh", "Account Executive"],
    "Phòng Marketing": ["Digital Marketing", "Content Creator", "Brand Manager", "Trưởng phòng Marketing"],
    "Phòng Tài chính - Kế toán": ["Kế toán viên", "Kế toán trưởng", "Chuyên viên Phân tích Tài chính"],
    "Phòng Công nghệ thông tin": ["Quản trị Hệ thống", "Database Administrator", "Kỹ sư Mạng", "Chuyên viên Bảo mật"],
    "Phòng Logistics": ["Warehouse Supervisor", "Điều phối viên", "Nhân viên Logistics"],
    "Phòng Nghiên cứu & Phát triển": ["Product Researcher", "Nghiên cứu viên", "Chuyên viên R&D"]
}

BANKS = ["Vietcombank", "Techcombank", "MB Bank", "BIDV", "VietinBank", "ACB", "TPBank", "VPBank", "Sacombank"]

def generate_sql():
    lines = []
    lines.append("-- DBeaver Seed Data for HRM (Oracle Database) - 500 Employees")
    lines.append("-- Chú ý: Cần bấm Alt + X (Execute Script) để chạy toàn bộ file.")
    lines.append("")
    lines.append("-- 1. Xóa dữ liệu cũ và reset sequence")
    lines.append("DELETE FROM tasks;")
    lines.append("DELETE FROM projects;")
    lines.append("DELETE FROM user_accounts;")
    lines.append("DELETE FROM employees;")
    lines.append("")
    lines.append("-- Reset identity column (Oracle 12c+)")
    lines.append("ALTER TABLE tasks MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);")
    lines.append("ALTER TABLE projects MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);")
    lines.append("")

    # Admin
    lines.append("-- 2. Insert dữ liệu Nhân viên Admin & 500 Employees")
    lines.append("""INSERT INTO employees (
    employee_id, full_name, date_of_birth, gender, email, phone, 
    address, employee_type, department, position, salary, 
    bank_name, account_number
) VALUES (
    'ADMIN001', 'Trần Văn Quản Trị', TO_DATE('1990-01-15', 'YYYY-MM-DD'), 'MALE', 'admin@company.com', '+84-901-234-567', 
    '123 Đường Nguyễn Huệ, Quận 1, TP.HCM', 'FULL_TIME', 'Ban Giám Đốc', 'Giám đốc Điều hành', 75000000.00, 
    'Vietcombank', '0123456789'
);""")

    # 500 Employees
    for i in range(1, 501):
        emp_id = f"EMP{i:03d}"
        gender = random.choice(["MALE", "FEMALE"])
        if gender == "MALE":
            name = f"{random.choice(LAST_NAMES)} {random.choice(FIRST_NAMES_MALE)} {random.choice(MID_NAMES_MALE)}"
        else:
            name = f"{random.choice(LAST_NAMES)} {random.choice(FIRST_NAMES_FEMALE)} {random.choice(MID_NAMES_FEMALE)}"
        
        dob_year = random.randint(1975, 2003)
        dob_month = random.randint(1, 12)
        dob_day = random.randint(1, 28)
        dob_str = f"{dob_year}-{dob_month:02d}-{dob_day:02d}"
        
        email = f"emp{i:03d}@company.com"
        phone = f"+84-9{random.randint(10,99)}-{random.randint(100,999)}-{random.randint(100,999)}"
        district = random.choice(["Quận 1", "Quận 3", "Quận 5", "Quận 7", "Quận Tân Bình", "Quận Bình Thạnh", "Quận Phú Nhuận"])
        address = f"{random.randint(1, 999)} Đường Nguyễn Trãi, {district}, TP.HCM"
        emp_type = random.choice(["FULL_TIME", "FULL_TIME", "FULL_TIME", "PART_TIME"])
        dept = random.choice(DEPARTMENTS)
        pos = random.choice(POSITIONS[dept])
        salary = round(random.uniform(12000000, 50000000), 2)
        bank = random.choice(BANKS)
        acc_num = "".join([str(random.randint(0, 9)) for _ in range(10)])

        lines.append(f"""INSERT INTO employees (
    employee_id, full_name, date_of_birth, gender, email, phone, 
    address, employee_type, department, position, salary, 
    bank_name, account_number
) VALUES (
    '{emp_id}', '{name}', TO_DATE('{dob_str}', 'YYYY-MM-DD'), '{gender}', '{email}', '{phone}', 
    '{address}', '{emp_type}', '{dept}', '{pos}', {salary:.2f}, 
    '{bank}', '{acc_num}'
);""")

    # User Accounts
    lines.append("\n-- 3. Insert dữ liệu Tài khoản (user_accounts)")
    lines.append("-- Password mặc định: admin123 -> Hash BCrypt: $2a$10$YDTWjFu3pQOOLaN6ICzx2u9XHlOd5W3TIJXlkbyPM75IYfrTseKbK")
    lines.append("INSERT INTO user_accounts (employee_id, password, role) VALUES ('ADMIN001', '$2a$10$YDTWjFu3pQOOLaN6ICzx2u9XHlOd5W3TIJXlkbyPM75IYfrTseKbK', 'ROLE_ADMIN');")
    for i in range(1, 501):
        emp_id = f"EMP{i:03d}"
        lines.append(f"INSERT INTO user_accounts (employee_id, password, role) VALUES ('{emp_id}', '$2a$10$YDTWjFu3pQOOLaN6ICzx2u9XHlOd5W3TIJXlkbyPM75IYfrTseKbK', 'ROLE_EMPLOYEE');")

    # Projects
    lines.append("\n-- 4. Insert dữ liệu Dự án (projects)")
    projects = [
        ("PRJ001", "Dự án Phát triển HRM nội bộ", "Xây dựng phân hệ quản lý nhân sự, chấm công và tính lương.", "ACTIVE"),
        ("PRJ002", "Dự án Website Thương mại Điện tử", "Thiết kế và lập trình website bán lẻ cho đối tác.", "ACTIVE"),
        ("PRJ003", "Dự án Nâng cấp Hệ thống CRM", "Tích hợp AI phân tích hành vi khách hàng.", "ACTIVE"),
        ("PRJ004", "Dự án Chuyển đổi số Kế toán", "Số hóa chứng từ và tự động hóa báo cáo thuế.", "ON_HOLD"),
        ("PRJ005", "Dự án Mobile App HRM", "Ứng dụng chấm công bằng khuôn mặt trên smartphone.", "ACTIVE")
    ]
    for p_code, name, desc, status in projects:
        lines.append(f"INSERT INTO projects (project_code, name, description, status) VALUES ('{p_code}', '{name}', '{desc}', '{status}');")

    # Tasks
    lines.append("\n-- 5. Insert dữ liệu Công việc (tasks)")
    tasks = [
        ("TSK001", "Thiết kế Database HRM", "Lên cấu trúc các bảng và quan hệ cho HRM", "2026-08-01", "DONE", 1, "EMP001"),
        ("TSK002", "Phát triển API Quản lý Task", "Tạo API CRUD cho Task và Project", "2026-08-10", "IN_PROGRESS", 1, "EMP001"),
        ("TSK003", "Thiết kế UI Website", "Vẽ wireframe và mockup cho trang chủ", "2026-08-05", "TODO", 2, "EMP002"),
        ("TSK004", "Kiểm thử bảo mật API", "Scan lỗ hổng OWASP và JWT Security", "2026-08-15", "TODO", 1, "EMP003"),
        ("TSK005", "Tích hợp Cổng thanh toán", "Kết nối VNPay & ZaloPay", "2026-08-20", "IN_PROGRESS", 2, "EMP004")
    ]
    for t_code, title, desc, deadline, status, p_id, a_id in tasks:
        lines.append(f"INSERT INTO tasks (task_code, title, description, deadline, status, project_id, assignee_id) VALUES ('{t_code}', '{title}', '{desc}', TO_DATE('{deadline}', 'YYYY-MM-DD'), '{status}', {p_id}, '{a_id}');")

    lines.append("\nCOMMIT;")

    with open("oracle_seed_data.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Successfully generated oracle_seed_data.sql with 500 employees!")

if __name__ == "__main__":
    generate_sql()
