# Spring Boot Main Configuration File
spring.profiles.active=prod
server.port=8080

# JWT Configuration
jwt.secret=c2VjcmV0S2V5Rm9ySFJNTWFuYWdlbWVudFN5c3RlbUpXVENvbXBhbnlBcHAyMDI2
jwt.expiration-ms=86400000
